# Generated by Django 4.2.7 on 2024-01-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pofile_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pofile',
            name='birthday',
            field=models.DateField(blank=True),
        ),
    ]
